spring:
  application:
    name: ai-core

spring.ai.openai:
  api-key: ${OPENAI_API_KEY}
  base-url: https://api.openai.com   # 默认就是这个，可以改成代理
  chat:
    options:
      model: gpt-4o-mini               # 模型名称（支持 gpt-4o, gpt-4o-mini 等）
      temperature: 0.7                 # 控制随机性（0 = 严谨，1 = 创造性）
      max-tokens: 500                  # 最大输出长度

# Doubao 配置
spring.ai.doubao:
  api-key: ${DOUBAO_API_KEY}
  base-url: https://ark.cn-beijing.volces.com
  model: doubao-seed-1-6-flash-250615
